backend:
  name: git-gateway
  branch: main # or master, depending on your branch name

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "products" # The name of your collection
    label: "Produits" # The label displayed in the CMS UI
    folder: "_data/products" # The folder where content files will be saved
    create: true # Allow users to create new products
    slug: "{{slug}}" # Create file names from the product name
    fields:
      - { label: "Nom du produit", name: "name", widget: "string", required: true }
      - { label: "Prix (CFA)", name: "price", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "text", required: true }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Message WhatsApp", name: "whatsapp", widget: "string", required: true }